name: Publish package to the Maven Central Repository

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: show version
      run: echo See ${{ github.ref_name }}

    - name: Build with Maven
      run: mvn --batch-mode --no-transfer-progress test -Drevision=${{ github.ref_name }}



